language: python
python:
  - "3.8"

before_install:
  - sudo apt-get install xvfb
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - sudo tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C /usr/bin
  - export PATH=$PATH:usr/bin/geckodriver

env:
  - MOZ_HEADLESS=1

# command to install dependencies
install:
  - pip install -r requirements.txt


addons:
  - firefox: latest

services:
  - postgresql
  - sqlite3

before_script:
  - sudo chmod a+x /usr/bin/geckodriver
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  # - sleep 5 # give xvfb some time to start

# command to run tests
script:
  - chmod +x manage.py
  - ./manage.py test search
  - ./manage.py test account