# Generated by Django 3.0.1 on 2021-03-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20200402_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coordinates', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='op_food',
            name='store_available',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
