# Generated by Django 3.0.1 on 2021-03-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20210310_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='op_food',
            name='store_available',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
