# Generated by Django 3.0.1 on 2021-04-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20210330_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='op_food',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Categorie'),
        ),
        migrations.AlterField(
            model_name='op_food',
            name='store_available',
            field=models.ManyToManyField(to='search.Store'),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='id_substitute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Op_food'),
        ),
    ]
